### ISSUE TITLE
Weird install error on Travis CI with Pip

### ISSUE THREAD

**Issue by NiklasRosenstein** [nodepy/nodepy#18]
```
6.46s$ sudo $PIP install git+https://github.com/nodepy/nodepy.git
The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/travis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/nodepy/nodepy.git
  Cloning https://github.com/nodepy/nodepy.git to /tmp/pip-16belnoj-build
Collecting localimport>=1.5.1 (from node.py==0.0.13)
  Downloading localimport-1.5.1.zip
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.4/dist-packages (from node.py==0.0.13)
Installing collected packages: localimport, node.py
  Running setup.py install for localimport ... done
  Running setup.py install for node.py ... error
    Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-16belnoj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lq_ksi51-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Installing Node.py and PPYM dependencies in a separate context ...
      Command: pip install localimport>=1.5.1 six>=1.10.0
    The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/travis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Requirement already satisfied: localimport>=1.5.1 in /usr/local/lib/python3.4/dist-packages
    Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.4/dist-packages
    running build
    running build_py
    Generating grammar tables from /usr/lib/python3.4/lib2to3/Grammar.txt
    Generating grammar tables from /usr/lib/python3.4/lib2to3/PatternGrammar.txt
    creating build
    creating build/lib
    copying nodepy.py -> build/lib
    running install_lib
    copying build/lib/nodepy.py -> /usr/local/lib/python3.4/dist-packages
    byte-compiling /usr/local/lib/python3.4/dist-packages/nodepy.py to nodepy.cpython-34.pyc
    running install_egg_info
    running egg_info
    creating node.py.egg-info
    writing top-level names to node.py.egg-info/top_level.txt
    writing requirements to node.py.egg-info/requires.txt
    writing dependency_links to node.py.egg-info/dependency_links.txt
    writing node.py.egg-info/PKG-INFO
    writing entry points to node.py.egg-info/entry_points.txt
    writing manifest file 'node.py.egg-info/SOURCES.txt'
    reading manifest file 'node.py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.rst'
    no previously-included directories found matching 'ppym/dist'
    no previously-included directories found matching 'ppym/nodepy_modules'
    writing manifest file 'node.py.egg-info/SOURCES.txt'
    Copying node.py.egg-info to /usr/local/lib/python3.4/dist-packages/node.py-0.0.13-py3.4.egg-info
    running install_scripts
    Installing node.py script to /usr/local/bin
    writing list of installed files to '/tmp/pip-lq_ksi51-record/install-record.txt'
    Bootstrapping PPYM dependencies with Pip ...
    The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/travis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Requirement already satisfied: appdirs>=1.4.2 in /usr/local/lib/python3.4/dist-packages
    Collecting hammock>=0.2.4
      Downloading hammock-0.2.4.tar.gz
    Collecting requests>=2.13.0
      Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    Collecting jsonschema>=2.6.0
      Downloading jsonschema-2.6.0-py2.py3-none-any.whl
    Collecting click>=6.7
      Downloading click-6.7-py2.py3-none-any.whl (71kB)
    Collecting distlib>=0.2.4
      Downloading distlib-0.2.4.zip (547kB)
    Installing collected packages: requests, hammock, jsonschema, click, distlib
      Running setup.py install for hammock: started
        Running setup.py install for hammock: finished with status 'done'
    Exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 922, in install
        with open(inst_files_path, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'nodepy_modules/.pip/lib/python3.4/site-packages/hammock-0.2.4-py3.4.egg-info/installed-files.txt'
    error: Pip installation failed
```

**Comment by NiklasRosenstein** [comment]
The `installed-files.txt` issue hasn't come up in a while now (while always working with Pip 9.0.1). Not carrying this issue over to [nodepy-pm](https://github.com/nodepy/nodepy-pm) for now.
